# Generated by Django 4.2.13 on 2024-05-27 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=1990)),
                ('price_per_day', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('penalty_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('deposit_returned', models.BooleanField(default=False)),
                ('deposit_amount', models.IntegerField(default=0)),
                ('rental_cost', models.IntegerField(default=0)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_park.autopark')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_park.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_park.carbrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_park.cartype'),
        ),
        migrations.CreateModel(
            name='AutoParkCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rented', models.BooleanField(default=False)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_park.autopark')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_park.car')),
            ],
        ),
        migrations.AddField(
            model_name='autopark',
            name='cars',
            field=models.ManyToManyField(blank=True, through='auto_park.AutoParkCar', to='auto_park.car'),
        ),
    ]
