# Generated by Django 4.2.13 on 2024-05-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='penalty_cost',
            field=models.IntegerField(default=0),
        ),
    ]
